### ISSUE TITLE
Amazon Price Tracker using python

### ISSUE THREAD

**Issue by pritamp17** [Tejas1510/Hacking-Scripts#58] opened 2021-01-06 07:59 UTC
### I'm submitting a 
- [x] bug report.
- [x] feature request.

**Comment by pritamp17** [comment] 2021-01-06 08:01
@Tejas1510 could you please assign this to me under SWOC?

**Comment by Tejas1510** [comment] 2021-01-06 08:08
go ahead @pritamp17

**Comment by amandp13** [comment] 2021-01-06 08:16
@Tejas1510 Assign me this issue. [SWOC 2021]

**Comment by Tejas1510** [comment] 2021-01-06 08:18
@amandp13 which language

**Comment by amandp13** [comment] 2021-01-06 08:35
@Tejas1510  Python

**Comment by pritamp17** [comment] 2021-01-07 11:49
@Tejas1510 sir, I have sent PR please do a review when you can.

**Comment by pritamp17** [comment] 2021-01-07 13:37
please close this issue, my PR has been merged

**Comment by Tejas1510** [comment] 2021-01-07 15:05
@pritamp17 the issue is still open in other language for other to work

**Comment by Tejas1510** [comment] 2021-01-07 15:06
@amandp13 we have a script in python, if you want to work on any other issue I will assign it to you

**Comment by pritamp17** [comment] 2021-01-07 15:48
@Tejas1510 I can try implementing in javascript, please assign me.

**Comment by tripathyprateek** [comment] 2021-01-12 21:22
@pritamp17 I guess you have a lot of issues assigned already. Lets get some PR merged and then get back to this.

**Comment by pritamp17** [comment] 2021-01-13 02:36
Ok

**Closed** 2021-01-24 14:46 UTC
Labels: Java, Javascript, Python, easy, swoc2021, up-for-grab
